baseURL = "https://albizago.github.io"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "it"
rssLimit = 10
theme = "hugo-texify3"
title = "Test"

[caches]
    [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 5

[taxonomies]
tags = "tags"
categories = "categories"
series = "series"

[params]
title="Albi's site"
description = "A simple personal page, with a blog for my random thoughts"
footnote = """
Made with  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> / Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true

[params.Author]
    name = "Alberto Zaghini"

[params.commentEngine]
code = " "

[params.buymeacoffee]
code = " "

[params.sharingbuttons]
facebook = false
x = false
twitter = false
email = false
linkedin = false
reddit = false
whatsapp = false
hackernews = false
telegram = false

[services]
    [services.googleAnalytics]
    id = " "

[menu]
    [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    pre = ""
    weight = 1

    [[menu.main]]
    identifier = "about"
    name = "Info"
    url = "/about/"
    pre = ""
    weight = 2